#####################################
# 2018 ithome ironman
# Author: James Lu
# Topic: k8s 不自賞 - Day 29 邁向 DevOps 之路 (2)
# Url: https://ithelp.ithome.com.tw/articles/10196286
# Licence: MIT
#####################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ithome-ingress
  namespace: develop
spec:
  backend:
    serviceName: ithome
    servicePort: 80